version: "2.2"

services:
  api:
    container_name: "fastapi-challenge-api"
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    environment:
      - DATABASE_URL=postgresql://fastapi:fastapi@db:5432/fastapi_challenge
      - AUTH_SECRET=fastapi_challenge
      - AUTH_ALGORITHM=HS256
    ports:
      - 5001:8080
    volumes:
      - ./api:/usr/src/app
    depends_on:
      db:
        condition: service_healthy

  nginx:
    container_name: "fastapi-challenge-nginx"
    build: ./docker/nginx
    ports:
      - 80:80
    depends_on:
      - api

  db:
    container_name: "fastapi-challenge-db"
    hostname: app_db
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./docker/db/dataset:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_DB=fastapi_challenge
    ports:
      - "65432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d fastapi_challenge -U fastapi"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: